# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/student job/Lab work/lab3/Camera_Emulation_Project_v2_lab3/Camera_Emulation_Project_v2_lab3.srcs/sources_1/ip/Dual_Port_BRAM/Dual_Port_BRAM.xci
# IP: The module: 'Dual_Port_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/student job/Lab work/lab3/Camera_Emulation_Project_v2_lab3/Camera_Emulation_Project_v2_lab3.srcs/sources_1/ip/Dual_Port_BRAM/Dual_Port_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dual_Port_BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: H:/student job/Lab work/lab3/Camera_Emulation_Project_v2_lab3/Camera_Emulation_Project_v2_lab3.srcs/sources_1/ip/Dual_Port_BRAM/Dual_Port_BRAM.xci
# IP: The module: 'Dual_Port_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/student job/Lab work/lab3/Camera_Emulation_Project_v2_lab3/Camera_Emulation_Project_v2_lab3.srcs/sources_1/ip/Dual_Port_BRAM/Dual_Port_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dual_Port_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
